"""Shared paths and helpers for the video pipeline.

Every script in video/ is run from the project root, e.g.

    python video/stage_2_tts.py

so all paths here are repo-root relative.
"""

import json
import re
from pathlib import Path

VIDEO_DIR = Path("video")
SHOTS_PATH = VIDEO_DIR / "shots.json"
ASSETS_DIR = VIDEO_DIR / "assets"          # inputs produced by stage 1 (trajectories, figures)
BUILD_DIR = VIDEO_DIR / "build"            # everything regenerated by stages 2-4

TRAJ_DIR = ASSETS_DIR / "trajectories"     # <name>.npz, one per sampled trajectory
FIG_DIR = ASSETS_DIR / "figures"           # PNG renders of paper figures
RESULTS_DIR = ASSETS_DIR / "results"       # real final results, used until trajectories exist
AUDIO_DIR = BUILD_DIR / "audio"            # <shot_id>.wav + durations.json
SHOT_VIDEO_DIR = BUILD_DIR / "shots"       # <shot_id>.mp4 (silent) from stage 3
MUXED_DIR = BUILD_DIR / "muxed"            # <shot_id>.mp4 with narration, from stage 4
DURATIONS_PATH = AUDIO_DIR / "durations.json"
SUBTITLE_CHARS = 130                       # max characters per subtitle chunk (two lines)
SUBTITLE_MIN_TAIL = 30                     # a shorter last chunk is merged into the previous one


def load_shots(path=SHOTS_PATH):
    """The shot list: title, render settings and one entry per shot."""
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_shots(data, path=SHOTS_PATH):
    Path(path).write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_durations(path=DURATIONS_PATH):
    """{shot_id: narration seconds}; empty when stage 2 has not run yet."""
    p = Path(path)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def shot_duration(shot, durations, settings):
    """Screen time of a shot: its narration plus the lead-in and tail padding.

    A shot without narration (or before stage 2 ran) falls back to its own "min_seconds"."""
    speech = float(durations.get(shot["id"], 0.0))
    padded = speech + settings["lead_in_s"] + settings["tail_s"] if speech > 0 else 0.0
    return max(padded, float(shot.get("min_seconds", settings["min_shot_s"])))


def select_shots(shots, only):
    """Filter shots by a comma-separated id list ("" keeps all)."""
    if not only:
        return shots
    wanted = {s.strip() for s in only.split(",") if s.strip()}
    missing = wanted - {s["id"] for s in shots}
    if missing:
        raise SystemExit(f"unknown shot id(s): {sorted(missing)}")
    return [s for s in shots if s["id"] in wanted]


def line_spans_key(shot_id):
    """durations.json key holding (start, end) of each narration line, in speech seconds."""
    return f"{shot_id}#lines"


def subtitle_timeline(text, speech_s, line_spans=None):
    """[(t0, t1, chunk)] in seconds from the start of speech.

    Each line of the narration (split at newlines) gets its own subtitles, never merged with
    the next line. Lines are placed at their measured spans when stage 2 recorded them, else
    in proportion to their length; chunks within a line are spread by their length."""
    lines = [ln.strip() for ln in (text or "").split("\n") if ln.strip()]
    if not lines:
        return [], []
    if not line_spans or len(line_spans) != len(lines):
        total, t, line_spans = sum(len(ln) for ln in lines), 0.0, []
        for ln in lines:
            d = speech_s * len(ln) / total
            line_spans.append((t, t + d))
            t += d
    out = []
    for ln, (a, b) in zip(lines, line_spans):
        chunks = split_subtitles(ln)
        w, t = sum(len(c) for c in chunks), float(a)
        for c in chunks:
            d = (float(b) - float(a)) * len(c) / w
            out.append((t, t + d, c))
            t += d
    return out, [tuple(sp) for sp in line_spans]


def split_subtitles(text, max_chars=SUBTITLE_CHARS):
    """Sentence-aware chunks of at most max_chars, each wrapped to two lines."""
    words, chunks, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > max_chars:
            chunks.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
        if re.search(r"[.!?]$", w) and len(cur) > max_chars * 0.45:
            chunks.append(cur)
            cur = ""
    if cur:
        chunks.append(cur)
    if len(chunks) > 1 and len(chunks[-1]) < SUBTITLE_MIN_TAIL:
        chunks[-2:] = [chunks[-2] + " " + chunks[-1]]
    wrapped = []
    for c in chunks:
        if len(c) > max_chars // 2:
            cut = c.rfind(" ", 0, len(c) // 2 + 8)
            c = c[:cut] + "\n" + c[cut + 1:] if cut > 0 else c
        wrapped.append(c)
    return wrapped
